#!/usr/bin/perl

my @a;

if ($#ARGV == -1) {
    while (<STDIN>) {
	chomp;
	push @a, $_;
    }
} else {
    @a = @ARGV;
}

foreach my $s (@a) {
    $s =~ s/\\/\\\\/g;
    $s =~ s/\(/\\(/g;
    $s =~ s/\)/\\)/g;
    $s =~ s/"/\\"/g;
    $s =~ s/'/\\'/g;
    $s =~ s/ /\\ /g;
    $s =~ s/#/\\#/g;
    $s =~ s/!/\\!/g;
    $s =~ s/\$/\\\$/g;
    print $s;
}
print "\n"
